# Generated by Django 5.1.1 on 2025-02-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_crops',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('company', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client_crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_clients.clientcrop')),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FECHA_COS', models.DateField(null=True)),
                ('NOM_HAC', models.CharField(blank=True, max_length=50, null=True)),
                ('STE', models.CharField(blank=True, max_length=50, null=True)),
                ('STE2', models.CharField(blank=True, max_length=50, null=True)),
                ('VAR', models.CharField(blank=True, max_length=50, null=True)),
                ('AREA', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('EDAD_COS', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('NCTE', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('SAC', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('TCH', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('TCHM', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('TAH', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('TAHM', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('REND_COM', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('MAT_EXT', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_clients.client')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_productions',
            },
        ),
        migrations.CreateModel(
            name='ClientSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STE', models.CharField(blank=True, max_length=50, null=True)),
                ('NOM_HAC', models.CharField(blank=True, max_length=50, null=True)),
                ('PROF', models.CharField(blank=True, max_length=50, null=True)),
                ('TEXT', models.CharField(blank=True, max_length=50, null=True)),
                ('pH', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Ca', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('P', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('MO', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Cea', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Pb', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('PO', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Mg', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Na', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('K', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('KNa', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Al', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('CIC', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('CaMg', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('CaMgK', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('B', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Cu', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Fe', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Mn', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('FeMn', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Zn', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('S', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Ar', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('L', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('A', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('N', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('CO', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('CN', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_clients.client')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_soils',
            },
        ),
    ]
