# Generated by Django 5.1.1 on 2025-02-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientproduction',
            name='FECHA_SIEM',
            field=models.DateField(null=True),
        ),
    ]
