# Generated by Django 5.1.1 on 2025-01-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0002_client_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='crop',
            new_name='client_crop',
        ),
    ]
