# Generated by Django 5.1.1 on 2025-01-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_clients', '0003_rename_crop_client_client_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientproduction',
            old_name='sac',
            new_name='AREA',
        ),
        migrations.RenameField(
            model_name='clientproduction',
            old_name='tch',
            new_name='EDAD_COS',
        ),
        migrations.RenameField(
            model_name='clientproduction',
            old_name='tchm',
            new_name='MAT_EXT',
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='FECHA_COS',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='NCTE',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='NOM_HAC',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='REND_COM',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='SAC',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='STE',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='TAH',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='TAHM',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='TCH',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='TCHM',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientproduction',
            name='VAR',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Al',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='B',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='CIC',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='CaMg',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='CaMgK',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Cea',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Cu',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Fe',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='FeMn',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='K',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='KNa',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Mg',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Mn',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Na',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='PO',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientsoil',
            name='Pb',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
